config/routes.rb
Rails.application.routes.draw do
  get 'contact/create'
  resources :proyectos, only: [:index]
  resources :habilidades
  resources :experiencias
  resources :educaciones
  post 'contact', to: 'contact#create'  # Corregido el nombre del controlador
  root 'proyectos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/educacion.rb
class Educacion < ApplicationRecord
end

app/models/habilidad.rb
class Habilidad < ApplicationRecord
end

app/models/proyecto.rb
class Proyecto < ApplicationRecord
    validates :titulo, :descripcion, :url, presence: true
    # Validaciones adicionales pueden ser agregadas aquí
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def create
    # Recupera los parámetros del formulario
    name = params[:name]
    email = params[:email]
    message = params[:message]

    # Aquí puedes llamar al mailer para enviar el correo
    ContactMailer.contact_email(name, email, message).deliver_now

    # Redirige a la página de index.html.erb en la carpeta views/proyectos
    redirect_to root_path, notice: 'Mensaje enviado correctamente.'
  end
end

app/controllers/educaciones_controller.rb
class EducacionesController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/experiencias_controller.rb
class ExperienciasController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/habilidades_controller.rb
class HabilidadesController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/proyectos_controller.rb
class ProyectosController < ApplicationController
  def index
    @proyectos = Proyecto.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/educaciones_helper.rb
module EducacionesHelper
end

app/helpers/experiencias_helper.rb
module ExperienciasHelper
end

app/helpers/habilidades_helper.rb
module HabilidadesHelper
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/views/contact/create.html.erb
<h1>Contact#create</h1>
<p>Find me in app/views/contact/create.html.erb</p>

app/views/educaciones/create.html.erb
<h1>Educaciones#create</h1>
<p>Find me in app/views/educaciones/create.html.erb</p>

app/views/educaciones/destroy.html.erb
<h1>Educaciones#destroy</h1>
<p>Find me in app/views/educaciones/destroy.html.erb</p>

app/views/educaciones/edit.html.erb
<h1>Educaciones#edit</h1>
<p>Find me in app/views/educaciones/edit.html.erb</p>

app/views/educaciones/index.html.erb
<h1>Educaciones#index</h1>
<p>Find me in app/views/educaciones/index.html.erb</p>

app/views/educaciones/new.html.erb
<h1>Educaciones#new</h1>
<p>Find me in app/views/educaciones/new.html.erb</p>

app/views/educaciones/update.html.erb
<h1>Educaciones#update</h1>
<p>Find me in app/views/educaciones/update.html.erb</p>

app/views/experiencias/create.html.erb
<h1>Experiencias#create</h1>
<p>Find me in app/views/experiencias/create.html.erb</p>

app/views/experiencias/destroy.html.erb
<h1>Experiencias#destroy</h1>
<p>Find me in app/views/experiencias/destroy.html.erb</p>

app/views/experiencias/edit.html.erb
<h1>Experiencias#edit</h1>
<p>Find me in app/views/experiencias/edit.html.erb</p>

app/views/experiencias/index.html.erb
<h1>Experiencias#index</h1>
<p>Find me in app/views/experiencias/index.html.erb</p>

app/views/experiencias/new.html.erb
<h1>Experiencias#new</h1>
<p>Find me in app/views/experiencias/new.html.erb</p>

app/views/experiencias/update.html.erb
<h1>Experiencias#update</h1>
<p>Find me in app/views/experiencias/update.html.erb</p>

app/views/habilidades/create.html.erb
<h1>Habilidades#create</h1>
<p>Find me in app/views/habilidades/create.html.erb</p>

app/views/habilidades/destroy.html.erb
<h1>Habilidades#destroy</h1>
<p>Find me in app/views/habilidades/destroy.html.erb</p>

app/views/habilidades/edit.html.erb
<h1>Habilidades#edit</h1>
<p>Find me in app/views/habilidades/edit.html.erb</p>

app/views/habilidades/index.html.erb
<h1>Habilidades#index</h1>
<p>Find me in app/views/habilidades/index.html.erb</p>

app/views/habilidades/new.html.erb
<h1>Habilidades#new</h1>
<p>Find me in app/views/habilidades/new.html.erb</p>

app/views/habilidades/update.html.erb
<h1>Habilidades#update</h1>
<p>Find me in app/views/habilidades/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Albertserv</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.12"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  <!-- Favicons -->
  <link rel="icon" type="image/x-icon" href="<%= asset_path 'favicon.ico' %>">
</head>

<body>
  <%= yield %>
</body>
</html>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    new Typed('#typed-name', {
      strings: ['Alberto Servin (>‿◠)✌', 'Web Designer (─‿‿─)', 'Entusiasta de la Tecnología (ɔ◔‿◔)ɔ ♥'],
      typeSpeed: 50,
      backSpeed: 25,
      backDelay: 2000,
      startDelay: 1000,
      loop: true
    });
  });
</script>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    const toggleButton = document.getElementById('dark-mode-toggle');
    const body = document.body;
    const moonIcon = '<i class="fa-solid fa-power-off"></i>';
    const sunIcon = '<i class="fa-solid fa-bolt"></i>';

    toggleButton.addEventListener('click', function() {
      body.classList.toggle('dark-mode');
      document.querySelectorAll('header, nav ul li a, section, label, footer').forEach(element => {
        element.classList.toggle('dark-mode');
      });

      if (body.classList.contains('dark-mode')) {
        toggleButton.innerHTML = sunIcon;
      } else {
        toggleButton.innerHTML = moonIcon;
      }
    });
  });
</script>

app/views/proyectos/create.html.erb
<h1>Proyectos#create</h1>
<p>Find me in app/views/proyectos/create.html.erb</p>

app/views/proyectos/destroy.html.erb
<h1>Proyectos#destroy</h1>
<p>Find me in app/views/proyectos/destroy.html.erb</p>

app/views/proyectos/edit.html.erb
<h1>Proyectos#edit</h1>
<p>Find me in app/views/proyectos/edit.html.erb</p>

app/views/proyectos/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Albertserv</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
</head>
<body>
  <header>
    <h1>Albertserv</h1>
    <nav>
      <ul>
        <li><a href="#about">Sobre mí</a></li>
        <li><a href="#tech-stack">Tecnologías</a></li>
        <li><a href="#education">Educación</a></li>
        <li><a href="#experience">Experiencia</a></li>
        <li><a href="#contact">Contacto</a></li>
      </ul>
    </nav>
    <button id="dark-mode-toggle"><i class="fa-solid fa-power-off"></i></button>
  </header>

  <main>
    <section id="introduction">
      <img src="<%= asset_path('yo_img.jpg') %>" alt="Mi Imagen">
      <h2 class="saludo">Hola a todos, soy <span id="typed-name"></span></h2>
      <p>Soy un programador apasionado por el desarrollo de software. Tengo experiencia en proyectos académicos y personales que han fortalecido mi capacidad para resolver problemas y crear soluciones innovadoras.</p>
    </section>

    <section id="about">
      <h2>Sobre mí</h2>
      <p>Me gradué en 2023 en Ingeniería en Informática en la Universidad Privada Del Este Sede C.D.E. donde adquirí una sólida base en lenguajes de programación y habilidades técnicas. Estoy motivado por la posibilidad de resolver problemas y crear soluciones innovadoras. Mi objetivo es seguir creciendo en el campo de la programación y contribuir a proyectos significativos. Me considero una persona curiosa y con ganas de aprender, siempre buscando mejorar mis conocimientos y habilidades.</p>
    </section>

    <section id="tech-stack">
      <h2>Tecnologías</h2>
      <ul class="tech-list">
        <% technologies = [
          { name: 'Ruby on Rails', svg: 'rubyonrails.svg' },
          { name: 'ReactJS', svg: 'reactjs.svg' },
          { name: 'Ruby', svg: 'ruby.svg' },
          { name: 'Python', svg: 'python.svg' },
          { name: 'NodeJS', svg: 'nodejs.svg' },
          { name: 'Express', svg: 'expressjs.png' },
          { name: 'MongoDB', svg: 'mongodb.svg' },
          { name: 'Postgresql', svg: 'pgsql.svg' },
          { name: 'mariaDB', svg: 'mariadb.svg' },
          { name: 'HTML', svg: 'html.svg'},
          { name: "JavaScript", svg: 'js.svg'},
          { name: 'tailwindCSS', svg: 'tailwind.svg' },
        ] %>

        <% technologies.each do |tech| %>
          <li>
            <%= image_tag(tech[:svg], alt: "#{tech[:name]} Logo") %>
            <span><%= tech[:name] %></span>
          </li>
        <% end %>
      </ul>
    </section>

    <section id="education">
      <h2>Educación</h2>
      <ul>
        <li>
          <h3>Ingeniería en Informática</h3>
          <p> U.P.E. filial Ciudad Del Este  (2018 - 2023)</p>
        </li>
        <li>
          <h3>Licenciatura en Análisis de Sistemas</h3>
          <p> U.P.E. filial Ciudad Del Este  (2018 - 2022)</p>
        </li>
        <li>
          <h3>Educación Media</h3>
          <h4>Nivel Medio(Tercer curso, Segundo curso, Primer curso)</h4>
          <p> Zenón Franco, Maria Roque Alonso (2017)</p>
          <p> Colegio Nacional San Blas (2015-2016)</p>
        </li>
        <li>
          <h3>Educación Básica</h3>
          <h4>Tercer Ciclo(Noveno grado, Octavo grado, Septimo grado)</h4>
          <p>Escuela y Colegio Nacional San Blas(2012 - 2014)</p>
        </li>
        <li>
          <h3>Educación Básica </h3>
          <h4>Segundo Ciclo(Quinto grado, Sexto grado)</h4>
          <p>Escuela y Colegio Nacional Kuarahy Resê(2010 - 2011)</p>
        </li>
        <li>
          <h3>Educación Básica </h3>
          <h4> Primer y Segundo Ciclo(cuarto grado, tercer grado, segundo grado, primer grado)</h4>
          <p>Escuela y Colegio Nacional Sagrada Familia(2006 - 2009)</p>
        </li>
      </ul>
    </section>

    <section id="experience">
      <h2>Experiencia</h2>
      <ul>
        <li>
          <h3>Neotelecom S.A.</h3>
          <h4>Analista de Datos y Desarrollo backend (Junio 2023 - Actualmente)</h4>
          <p>* Desarrollo de sistemas en Node.js y Express.js</p>
          <p>* Desarrollo de apis Azure Function en Python y C#</p>
          <p>* Desarrollo de aplicaciones de escritorio en python</p>
          <p>* Desarrollo de backend en Python, Flask y Django </p>
        </li>
      </ul>

      <ul>
        <li>
          <h3>Neotelecom S.A.</h4>
          <h4>Asistente de R.M.A. (Febrero 2023 - Junio 2023)</h4>
          <p>* Testeo y configuración de Routers</p>
        </li>
      </ul>

      <ul>
        <li>
          <h3>Fusión Electromecánica</h4>
          <h4>Desarrollo de sistema de Telemetría (Abril 2023 - Diciembre 2023)</h4>
          <p>* Desarrollo de sistema en Node-Red.js, grafana, docker, influxDB</p>
          <p>* Configuración de dispositivos Electrónicos con protocolo MQTT</p>
        </li>
      </ul>
    </section>

    <section id="contact">
  <h2>Contacto</h2>
  <%= form_with url: contact_path, method: :post, local: true do %>
    <label for="name">Nombre</label>
    <%= text_field_tag :name, nil, id: 'name', required: true %>

    <label for="email">Email</label>
    <%= email_field_tag :email, nil, id: 'email', required: true %>

    <label for="message">Mensaje</label>
    <%= text_area_tag :message, nil, id: 'message', required: true %>

    <%= submit_tag 'Enviar', class: 'submit-button' %>
  <% end %>
</section>

  </main>

  <footer>
    <p>&copy; 2024 Albertserv</p>
  </footer>
</body>
</html>

app/views/proyectos/new.html.erb
<h1>Proyectos#new</h1>
<p>Find me in app/views/proyectos/new.html.erb</p>

app/views/proyectos/show.html.erb
<h1>Proyectos#show</h1>
<p>Find me in app/views/proyectos/show.html.erb</p>

app/views/proyectos/update.html.erb
<h1>Proyectos#update</h1>
<p>Find me in app/views/proyectos/update.html.erb</p>